//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfirmSeat
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Journey_Date { get; set; }
        public string Start_Station { get; set; }
        public string End_Station { get; set; }
        public Nullable<int> TrainDetail { get; set; }
        public Nullable<int> TrainSchedule { get; set; }
        public Nullable<int> Seats { get; set; }
        public Nullable<decimal> Bill { get; set; }
        public Nullable<int> Seat_No { get; set; }
        public string PRN { get; set; }
    }
}
