//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainDetail()
        {
            this.TrainSchedule = new HashSet<TrainSchedule>();
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int Id { get; set; }
        public string TrainName { get; set; }
        public string Status { get; set; }
        public string RouteId { get; set; }
        public Nullable<int> No_of_compartment { get; set; }
        public Nullable<int> C1AC { get; set; }
        public Nullable<int> C2AC { get; set; }
        public Nullable<int> C3AC { get; set; }
        public Nullable<int> Sleeper { get; set; }
        public Nullable<int> General { get; set; }
        public string Day { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainSchedule> TrainSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
